//
// SimcirJS - library
//
// Copyright (c) 2014 Kazuhiko Arase
//
// URL: http://www.d-project.com/
//
// Licensed under the MIT license:
//  http://www.opensource.org/licenses/mit-license.php
//

// includes following device types:
//  RS-FF
//  JK-FF
//  T-FF

simcir.registerDevice('RS-FF',
{
  "width":600,
  "height":200,
  "showToolbox":false,
  "toolbox":[
    {"type":"In"},
    {"type":"Out"},
    {"type":"DC"},
    {"type":"PushOff"},
    {"type":"PushOn"},
    {"type":"Toggle"},
    {"type":"NAND"}
  ],
  "devices":[
    {"type":"In","id":"dev0","x":216,"y":112,"label":"~R"},
    {"type":"NAND","id":"dev1","x":264,"y":56,"label":"NAND"},
    {"type":"Out","id":"dev2","x":312,"y":56,"label":"Q"},
    {"type":"Out","id":"dev3","x":312,"y":104,"label":"~Q"},
    {"type":"DC","id":"dev4","x":104,"y":80,"label":"DC"},
    {"type":"PushOff","id":"dev5","x":160,"y":48,"label":"PushOff"},
    {"type":"PushOff","id":"dev6","x":160,"y":112,"label":"PushOff"},
    {"type":"In","id":"dev7","x":216,"y":48,"label":"~S"},
    {"type":"NAND","id":"dev8","x":264,"y":104,"label":"NAND"}
  ],
  "connectors":[
    {"from":"dev0.in0","to":"dev6.out0"},
    {"from":"dev1.in0","to":"dev7.out0"},
    {"from":"dev1.in1","to":"dev8.out0"},
    {"from":"dev2.in0","to":"dev1.out0"},
    {"from":"dev3.in0","to":"dev8.out0"},
    {"from":"dev5.in0","to":"dev4.out0"},
    {"from":"dev6.in0","to":"dev4.out0"},
    {"from":"dev7.in0","to":"dev5.out0"},
    {"from":"dev8.in0","to":"dev1.out0"},
    {"from":"dev8.in1","to":"dev0.out0"}
  ]
}
);

simcir.registerDevice('JK-FF',
{
  "width":600,
  "height":240,
  "showToolbox":true,
  "toolbox":[
    {"type":"In"},
    {"type":"Out"},
    {"type":"DC"},
    {"type":"PushOff"},
    {"type":"PushOn"},
    {"type":"Toggle"},
    {"type":"NAND"},
    {"type":"NAND","numInputs":3},
    {"type":"NOT"},
    {"type":"RS-FF"}
  ],
  "devices":[
    {"type":"RS-FF","id":"dev0","x":224,"y":120,"label":"RS-FF"},
    {"type":"NAND","id":"dev1","x":304,"y":152,"label":"NAND"},
    {"type":"NAND","id":"dev2","x":304,"y":88,"label":"NAND"},
    {"type":"In","id":"dev3","x":128,"y":120,"label":"CLK"},
    {"type":"In","id":"dev4","x":128,"y":72,"label":"J"},
    {"type":"In","id":"dev5","x":128,"y":168,"label":"K"},
    {"type":"RS-FF","id":"dev6","x":352,"y":120,"label":"RS-FF"},
    {"type":"NOT","id":"dev7","x":184,"y":32,"label":"NOT"},
    {"type":"Out","id":"dev8","x":432,"y":88,"label":"Q"},
    {"type":"Out","id":"dev9","x":432,"y":152,"label":"~Q"},
    {"type":"PushOn","id":"dev10","x":80,"y":120,"label":"PushOn"},
    {"type":"Toggle","id":"dev11","x":80,"y":168,"label":"Toggle"},
    {"type":"Toggle","id":"dev12","x":80,"y":72,"label":"Toggle"},
    {"type":"NAND","numInputs":3,"id":"dev13","x":176,"y":88,"label":"NAND"},
    {"type":"NAND","numInputs":3,"id":"dev14","x":176,"y":152,"label":"NAND"},
    {"type":"DC","id":"dev15","x":32,"y":120,"label":"DC"}
  ],
  "connectors":[
    {"from":"dev0.in0","to":"dev13.out0"},
    {"from":"dev0.in1","to":"dev14.out0"},
    {"from":"dev1.in0","to":"dev0.out1"},
    {"from":"dev1.in1","to":"dev7.out0"},
    {"from":"dev2.in0","to":"dev7.out0"},
    {"from":"dev2.in1","to":"dev0.out0"},
    {"from":"dev3.in0","to":"dev10.out0"},
    {"from":"dev4.in0","to":"dev12.out0"},
    {"from":"dev5.in0","to":"dev11.out0"},
    {"from":"dev6.in0","to":"dev2.out0"},
    {"from":"dev6.in1","to":"dev1.out0"},
    {"from":"dev7.in0","to":"dev3.out0"},
    {"from":"dev8.in0","to":"dev6.out0"},
    {"from":"dev9.in0","to":"dev6.out1"},
    {"from":"dev10.in0","to":"dev15.out0"},
    {"from":"dev11.in0","to":"dev15.out0"},
    {"from":"dev12.in0","to":"dev15.out0"},
    {"from":"dev13.in0","to":"dev6.out1"},
    {"from":"dev13.in1","to":"dev4.out0"},
    {"from":"dev13.in2","to":"dev3.out0"},
    {"from":"dev14.in0","to":"dev3.out0"},
    {"from":"dev14.in1","to":"dev5.out0"},
    {"from":"dev14.in2","to":"dev6.out0"}
  ]
}
);

simcir.registerDevice('T-FF',
{
  "width":600,
  "height":200,
  "showToolbox":true,
  "toolbox":[
    {"type":"In"},
    {"type":"Out"},
    {"type":"DC"},
    {"type":"LED"},
    {"type":"PushOff"},
    {"type":"PushOn"},
    {"type":"Toggle"},
    {"type":"BUF"},
    {"type":"NOT"},
    {"type":"AND"},
    {"type":"NAND"},
    {"type":"OR"},
    {"type":"NOR"},
    {"type":"EOR"},
    {"type":"ENOR"},
    {"type":"OSC"},
    {"type":"7seg"},
    {"type":"16seg"},
    {"type":"4bit7seg"},
    {"type":"RotaryEncoder"},
    {"type":"BusIn"},
    {"type":"BusOut"},
    {"type":"RS-FF"},
    {"type":"JK-FF"}
  ],
  "devices":[
    {"type":"JK-FF","id":"dev0","x":240,"y":72,"label":"JK-FF"},
    {"type":"In","id":"dev1","x":176,"y":56,"label":"T"},
    {"type":"In","id":"dev2","x":176,"y":104,"label":"CLK"},
    {"type":"Out","id":"dev3","x":336,"y":56,"label":"Q"},
    {"type":"Out","id":"dev4","x":336,"y":104,"label":"~Q"},
    {"type":"DC","id":"dev5","x":88,"y":56,"label":"DC"},
    {"type":"PushOn","id":"dev6","x":88,"y":104,"label":"PushOn"}
  ],
  "connectors":[
    {"from":"dev0.in0","to":"dev1.out0"},
    {"from":"dev0.in1","to":"dev2.out0"},
    {"from":"dev0.in2","to":"dev1.out0"},
    {"from":"dev1.in0","to":"dev5.out0"},
    {"from":"dev2.in0","to":"dev6.out0"},
    {"from":"dev3.in0","to":"dev0.out0"},
    {"from":"dev4.in0","to":"dev0.out1"},
    {"from":"dev6.in0","to":"dev5.out0"}
  ]
}
);

simcir.registerDevice('8bitCounter',
{
  "width":800,
  "height":400,
  "showToolbox":true,
  "toolbox":[
  ],
  "devices":[
    {"type":"T-FF","id":"dev0","x":136,"y":16,"label":"T-FF"},
    {"type":"T-FF","id":"dev1","x":136,"y":64,"label":"T-FF"},
    {"type":"T-FF","id":"dev2","x":136,"y":112,"label":"T-FF"},
    {"type":"T-FF","id":"dev3","x":136,"y":160,"label":"T-FF"},
    {"type":"T-FF","id":"dev4","x":136,"y":208,"label":"T-FF"},
    {"type":"T-FF","id":"dev5","x":136,"y":256,"label":"T-FF"},
    {"type":"T-FF","id":"dev6","x":136,"y":304,"label":"T-FF"},
    {"type":"T-FF","id":"dev7","x":136,"y":352,"label":"T-FF"},
    {"type":"Out","id":"dev8","x":216,"y":16,"label":"D0"},
    {"type":"Out","id":"dev9","x":216,"y":64,"label":"D1"},
    {"type":"Out","id":"dev10","x":216,"y":112,"label":"D2"},
    {"type":"Out","id":"dev11","x":216,"y":160,"label":"D3"},
    {"type":"Out","id":"dev12","x":216,"y":208,"label":"D4"},
    {"type":"Out","id":"dev13","x":216,"y":256,"label":"D5"},
    {"type":"Out","id":"dev14","x":216,"y":304,"label":"D6"},
    {"type":"Out","id":"dev15","x":216,"y":352,"label":"D7"},
    {"type":"In","id":"dev16","x":88,"y":16,"label":"T"},
    {"type":"In","id":"dev17","x":88,"y":64,"label":"CLK"},
    {"type":"DC","id":"dev18","x":40,"y":16,"label":"DC"},
    {"type":"PushOn","id":"dev19","x":40,"y":64,"label":"PushOn"}
  ],
  "connectors":[
    {"from":"dev0.in0","to":"dev16.out0"},
    {"from":"dev0.in1","to":"dev17.out0"},
    {"from":"dev1.in0","to":"dev16.out0"},
    {"from":"dev1.in1","to":"dev0.out0"},
    {"from":"dev2.in0","to":"dev16.out0"},
    {"from":"dev2.in1","to":"dev1.out0"},
    {"from":"dev3.in0","to":"dev16.out0"},
    {"from":"dev3.in1","to":"dev2.out0"},
    {"from":"dev4.in0","to":"dev16.out0"},
    {"from":"dev4.in1","to":"dev3.out0"},
    {"from":"dev5.in0","to":"dev16.out0"},
    {"from":"dev5.in1","to":"dev4.out0"},
    {"from":"dev6.in0","to":"dev16.out0"},
    {"from":"dev6.in1","to":"dev5.out0"},
    {"from":"dev7.in0","to":"dev16.out0"},
    {"from":"dev7.in1","to":"dev6.out0"},
    {"from":"dev8.in0","to":"dev0.out0"},
    {"from":"dev9.in0","to":"dev1.out0"},
    {"from":"dev10.in0","to":"dev2.out0"},
    {"from":"dev11.in0","to":"dev3.out0"},
    {"from":"dev12.in0","to":"dev4.out0"},
    {"from":"dev13.in0","to":"dev5.out0"},
    {"from":"dev14.in0","to":"dev6.out0"},
    {"from":"dev15.in0","to":"dev7.out0"},
    {"from":"dev16.in0","to":"dev18.out0"},
    {"from":"dev17.in0","to":"dev19.out0"},
    {"from":"dev19.in0","to":"dev18.out0"}
  ]
}
);